package day7

import (
	"testing"

	"github.com/jannes-io/aoc2025/pkg/testlib"
)

const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func Test(t *testing.T) {
	testlib.Assert(t, Part1(input), "21")
	testlib.Assert(t, Part2(input), "40")
}
